from django.urls import path
from Vendas.views import *
from Vendas.views import ProdutoListView, VendaDetailView

urlpatterns = [
    path('', index, name='index'),
    path('login', login, name='login_sem_barra'),
    path('login/', login, name='login'),
    path('logout/', logout_view, name='logout'),
    path('cadastro', cadastro_usuario, name='cadastro_sem_barra'),
    path('cadastro/', cadastro_usuario, name='cadastro'),
    path('usuario/editar/<int:id>/', editar_usuario, name='editar_usuario'),
    path('usuario/excluir/<int:id>/', excluir_usuario, name='excluir_usuario'),
    path('categorias/', categorias, name='categorias'),
    path('categoria/criar/', criar_categoria, name='criar_categoria'),
    path('categoria/editar/<int:categoria_id>/', editar_categoria, name='editar_categoria'),
    path('categoria/excluir/<int:categoria_id>/', excluir_categoria, name='excluir_categoria'),
    path('categoria/filtrar/', filtrar_categorias, name='filtrar_categorias'),
    path('mercadorias/', mercadorias, name='mercadorias'),
    path('mercadorias/<int:categoria_id>/', mercadorias, name='mercadorias_categoria'),
    path('mercadoria/criar/', criar_mercadoria, name='criar_mercadoria'),
    path('mercadoria/editar/<int:mercadoria_id>/', editar_mercadoria, name='editar_mercadoria'),
    path('mercadoria/excluir/<int:mercadoria_id>/', excluir_mercadoria, name='excluir_mercadoria'),
    path('mercadoria/filtrar/', filtrar_mercadorias, name='filtrar_mercadorias'),
    path('produtos/', ProdutoListView.as_view(), name='produtos'),
    path('produtos/<int:mercadoria_id>/', produtos_por_mercadoria, name='produtos_por_mercadoria'),
    path('produto/criar/', criar_produto, name='criar_produto'),
    path('produto/editar/<int:produto_id>/', editar_produto, name='editar_produto'),
    path('produto/excluir/<int:produto_id>/', excluir_produto, name='excluir_produto'),
    path('produto/filtrar/', filtrar_produtos, name='filtrar_produtos'),
    path('perfil/', perfil, name='perfil'),
    path('venda/<int:pk>/', VendaDetailView.as_view(), name='venda_detail'),
    path('vendas/', lista_vendas, name='lista_vendas'),
    path('venda/criar/', criar_venda, name='criar_venda'),
    path('venda/<int:pk>/editar/', editar_venda, name='editar_venda'),
    path('estoque/', lista_estoque, name='lista_estoque'),
    path('estoque/criar/', criar_estoque, name='criar_estoque'),
    path('estoque/<int:estoque_id>/editar/', editar_estoque, name='editar_estoque'),
    path('api/register/', api_register, name='api_register'),
]