# Generated by Django 6.0.5 on 2026-05-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='minimo_quantidade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
