# Generated by Django 6.0.5 on 2026-05-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0004_alter_estoque_minimo_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='minimo_quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
