# Generated by Django 6.0.5 on 2026-05-28 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0007_alter_user_email_alter_user_idade_alter_user_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='produto',
            new_name='produto_id',
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente_id',
            field=models.ForeignKey(db_column='cliente_id_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RenameField(
            model_name='venda',
            old_name='cliente_id',
            new_name='usuario_id',
        ),
        migrations.AlterField(
            model_name='venda_produto',
            name='produto_id',
            field=models.ForeignKey(db_column='produto_id_id', on_delete=django.db.models.deletion.CASCADE, to='Vendas.produto'),
        ),
        migrations.AlterField(
            model_name='venda_produto',
            name='venda_id',
            field=models.ForeignKey(db_column='venda_id_id', on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='Vendas.venda'),
        ),
    ]
