# Generated by Django 6.0.5 on 2026-06-02 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0008_alter_usuario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumoFinanceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faturamento_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
    ]
