# Generated by Django 6.0.5 on 2026-06-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0010_categoria_imagem_mercadoria_imagem_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('carrinho', 'Carrinho'), ('finalizada', 'Finalizada')], default='carrinho', max_length=20),
        ),
    ]
