# Generated by Django 6.0.5 on 2026-06-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Vendas', '0011_venda_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='estoque',
            unique_together={('produto_id',)},
        ),
    ]
